truncate disease_groups cascade;
truncate vaccine_aliases cascade;
insert into disease_groups (vaccine,group_code,disease_group,status,display_order) values ('Hexa','DTP_POLIO_COMBO','POLIO,DIPHTHERIA,TETANUS,PERTUSSIS,HIB,HEPB','ACTIVE',10);
insert into disease_groups (vaccine,group_code,disease_group,status,display_order) values ('Penta','DTP_POLIO_COMBO','POLIO,DIPHTHERIA,TETANUS,PERTUSSIS,HIB','ACTIVE',20);
insert into disease_groups (vaccine,group_code,disease_group,status,display_order) values ('Tetra','DTP_POLIO_COMBO','POLIO,DIPHTHERIA,TETANUS,PERTUSSIS','ACTIVE',30);
insert into disease_groups (vaccine,group_code,disease_group,status,display_order) values ('MMR','MMR','MEASLES,MUMPS,RUBELLA','ACTIVE',40);
insert into disease_groups (vaccine,group_code,disease_group,status,display_order) values ('JE','JE','JAPANESE_ENCEPHALITIS','ACTIVE',50);
insert into disease_groups (vaccine,group_code,disease_group,status,display_order) values ('INFLUENZA_IM','INFLUENZA','INFLUENZA','ACTIVE',60);
insert into disease_groups (vaccine,group_code,disease_group,status,display_order) values ('INFLUENZA_NASAL','INFLUENZA','INFLUENZA','ACTIVE',70);
insert into disease_groups (vaccine,group_code,disease_group,status,display_order) values ('Rotarix','ROTAVIRUS','ROTAVIRUS','ACTIVE',80);
insert into disease_groups (vaccine,group_code,disease_group,status,display_order) values ('ROTATEQ','ROTAVIRUS','ROTAVIRUS','ACTIVE',90);
insert into disease_groups (vaccine,group_code,disease_group,status,display_order) values ('PCV13','PCV','PNEUMOCOCCAL','ACTIVE',100);
insert into disease_groups (vaccine,group_code,disease_group,status,display_order) values ('PCV14','PCV','PNEUMOCOCCAL','ACTIVE',110);
insert into disease_groups (vaccine,group_code,disease_group,status,display_order) values ('PCV15','PCV','PNEUMOCOCCAL','ACTIVE',120);
insert into disease_groups (vaccine,group_code,disease_group,status,display_order) values ('PCV20','PCV','PNEUMOCOCCAL','ACTIVE',130);
insert into disease_groups (vaccine,group_code,disease_group,status,display_order) values ('HPV4','HPV','HPV','ACTIVE',140);
insert into disease_groups (vaccine,group_code,disease_group,status,display_order) values ('HPV9','HPV','HPV','ACTIVE',150);
insert into disease_groups (vaccine,group_code,disease_group,status,display_order) values ('RSV_ENFLONSIA','RSV','RSV','ACTIVE',160);
insert into disease_groups (vaccine,group_code,disease_group,status,display_order) values ('RSV_BEYFORTUS','RSV','RSV','ACTIVE',170);
insert into disease_groups (vaccine,group_code,disease_group,status,display_order) values ('VAR','VARICELLA','VARICELLA','ACTIVE',180);
insert into disease_groups (vaccine,group_code,disease_group,status,display_order) values ('DEN','DENGUE','DENGUE','ACTIVE',190);
insert into disease_groups (vaccine,group_code,disease_group,status,display_order) values ('HAV','HEPATITIS_A','HEPATITIS_A','ACTIVE',200);
insert into disease_groups (vaccine,group_code,disease_group,status,display_order) values ('ENTRO','ENTEROVAC','ENTEROVAC','ACTIVE',210);
insert into disease_groups (vaccine,group_code,disease_group,status,display_order) values ('MEN_B_BEXSERO','MENINGOCOCCAL','MENINGOCOCCAL_B','ACTIVE',220);
insert into disease_groups (vaccine,group_code,disease_group,status,display_order) values ('MEN_ACWY','MENINGOCOCCAL','MENINGOCOCCAL_ACWY','ACTIVE',230);
insert into disease_groups (vaccine,group_code,disease_group,status,display_order) values ('HBV','HEPATITIS_B','HEPATITIS_B','ACTIVE',240);
insert into disease_groups (vaccine,group_code,disease_group,status,display_order) values ('RABIES','RABIES','RABIES','ACTIVE',250);
insert into vaccine_aliases (group_code,alias) values ('DTP_POLIO_COMBO','hexa') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('DTP_POLIO_COMBO','6in1') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('DTP_POLIO_COMBO','6โรค') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('DTP_POLIO_COMBO','วัคซีนรวม6โรค') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('DTP_POLIO_COMBO','วัคซีนรวม หก โรค') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('DTP_POLIO_COMBO','ipv-dtp-hb-hib') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('DTP_POLIO_COMBO','โปลิโอ คอตีบ ไอกรน ปาดทะยัก ฮิป ตับอักเสบบี') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('DTP_POLIO_COMBO','penta') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('DTP_POLIO_COMBO','5in1') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('DTP_POLIO_COMBO','5โรค') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('DTP_POLIO_COMBO','วัคซีนรวม5โรค') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('DTP_POLIO_COMBO','ipv-dtp-hib') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('DTP_POLIO_COMBO','โปลิโอ คอตีบ ไอกรน ปาดทะยัก ฮิป') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('DTP_POLIO_COMBO','tetra') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('DTP_POLIO_COMBO','4in1') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('DTP_POLIO_COMBO','4โรค') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('DTP_POLIO_COMBO','วัคซีนรวม4โรค') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('DTP_POLIO_COMBO','ipv-dtp') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('DTP_POLIO_COMBO','dtap-ipv') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('DTP_POLIO_COMBO','โปลิโอ คอตีบ ไอกรน ปาดทะยัก') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('MMR','mmr') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('MMR','หัด') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('MMR','คางทูม') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('MMR','หัดเยอรมัน') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('JE','je') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('JE','ไข้สมองอักเสบเจอี') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('JE','เจอี') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('INFLUENZA','influenza_im:influenza im') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('INFLUENZA','flu') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('INFLUENZA','ไข้หวัดใหญ่') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('INFLUENZA','วัคซีนไข้หวัดใหญ่') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('INFLUENZA','วัคซีนไข้หวัดใหญ่ชนิดฉีด') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('INFLUENZA','influenza_nasal:influenza nasal') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('INFLUENZA','flu nasal') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('INFLUENZA','ไข้หวัดใหญ่พ่นจมูก') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('INFLUENZA','วัคซีนไข้หวัดใหญ่ชนิดพ่นจมูก') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('ROTAVIRUS','rotarix') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('ROTAVIRUS','โรต้า') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('ROTAVIRUS','วัคซีนโรต้า') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('ROTAVIRUS','โรต้า 1 สายพันธ์') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('ROTAVIRUS','rotateq') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('ROTAVIRUS','โรต้า 5 สายพันธ์') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('PCV','pcv13') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('PCV','ipd13') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('PCV','ipd') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('PCV','pcv') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('PCV','วัคซีนปอดอักเสบ') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('PCV','นิวโมคอคคัส') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('PCV','ไอพีดี') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('PCV','pcv14') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('PCV','ipd14') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('PCV','pcv15') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('PCV','ipd15') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('PCV','pcv20') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('PCV','ipd20') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('HPV','hpv4') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('HPV','hpv') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('HPV','มะเร็งปากมดลูก') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('HPV','หูดหงอนไก่') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('HPV','หูด') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('HPV','มะเร็ง') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('HPV','hpv9') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('HPV','หูดหงอนไก่หูด') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('RSV','rsv') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('RSV','enflonsia') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('RSV','ภูมิสำเร็จรูป rsv ภูมิคุ้มกันสำเร็จรูป ภูมิ rsv') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('RSV','nirsevimab') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('RSV','beyfortus') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('VARICELLA','varicella') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('VARICELLA','อีสุกอีใส') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('VARICELLA','วัคซีนอีสุกอีใส') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('DENGUE','dengue') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('DENGUE','ไข้เลือดออก') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('DENGUE','qdenga') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('HEPATITIS_A','hepatitis a') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('HEPATITIS_A','hav') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('HEPATITIS_A','ไวรัสตับอักเสบเอ') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('ENTEROVAC','entrovac') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('ENTEROVAC','ev71') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('ENTEROVAC','มือเท้าปาก') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('ENTEROVAC','วัคซีนมือเท้าปาก') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('ENTEROVAC','enterovirus71') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('MENINGOCOCCAL','bexsero') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('MENINGOCOCCAL','menb') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('MENINGOCOCCAL','ไข้กาฬหลังแอ่นบี') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('MENINGOCOCCAL','ไข้กาฬหลังแอ่นชนิดบี') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('MENINGOCOCCAL','menacwy') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('MENINGOCOCCAL','acwy') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('MENINGOCOCCAL','ไข้กาฬหลังแอ่น acwy') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('MENINGOCOCCAL','วัคซีนเดินทาง') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('HEPATITIS_B','hepatitis b') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('HEPATITIS_B','hbv') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('HEPATITIS_B','ไวรัสตับอักเสบบี') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('HEPATITIS_B','วัคซีนตับอักเสบบี') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('HEPATITIS_B','ตับบี') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('HEPATITIS_B','แม่เป็นพาหะตับบี') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('HEPATITIS_B','มารดาเป็นพาหะตับอักเสบบี') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('HEPATITIS_B','มารดา hbsag positive') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('RABIES','rabies') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('RABIES','พิษสุนัขบ้า') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('RABIES','วัคซีนพิษสุนัขบ้า') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('RABIES','สุนัขกัด') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('RABIES','แมวกัด') on conflict do nothing;
insert into vaccine_aliases (group_code,alias) values ('RABIES','สัตว์กัด') on conflict do nothing;

truncate age_guide cascade;
insert into age_guide (age_code,display_name,sort_order) values ('NB','แรกเกิด',1) on conflict (age_code) do nothing;
insert into age_guide (age_code,display_name,sort_order) values ('1M','1 เดือน',1.5) on conflict (age_code) do nothing;
insert into age_guide (age_code,display_name,sort_order) values ('2M','2 เดือน',2) on conflict (age_code) do nothing;
insert into age_guide (age_code,display_name,sort_order) values ('4M','4 เดือน',3) on conflict (age_code) do nothing;
insert into age_guide (age_code,display_name,sort_order) values ('6M','6 เดือน',4) on conflict (age_code) do nothing;
insert into age_guide (age_code,display_name,sort_order) values ('7M','7 เดือน',5) on conflict (age_code) do nothing;
insert into age_guide (age_code,display_name,sort_order) values ('9M','9 เดือน',6) on conflict (age_code) do nothing;
insert into age_guide (age_code,display_name,sort_order) values ('12M','1 ปี (12 เดือน)',7) on conflict (age_code) do nothing;
insert into age_guide (age_code,display_name,sort_order) values ('15M','15 เดือน',8) on conflict (age_code) do nothing;
insert into age_guide (age_code,display_name,sort_order) values ('18M','18 เดือน',9) on conflict (age_code) do nothing;
insert into age_guide (age_code,display_name,sort_order) values ('24M','2 ปี',10) on conflict (age_code) do nothing;
insert into age_guide (age_code,display_name,sort_order) values ('36M','3 ปี',11) on conflict (age_code) do nothing;
insert into age_guide (age_code,display_name,sort_order) values ('48M','4 ปี',12) on conflict (age_code) do nothing;
insert into age_guide (age_code,display_name,sort_order) values ('51M','4 ปี 3 เดือน',13) on conflict (age_code) do nothing;
insert into age_guide (age_code,display_name,sort_order) values ('132M','11 ปี',14) on conflict (age_code) do nothing;
insert into age_guide (age_code,display_name,sort_order) values ('138M','11 ปี ครึ่ง',15) on conflict (age_code) do nothing;
insert into age_guide (age_code,display_name,sort_order) values ('ALL_AGES',NULL,99) on conflict (age_code) do nothing;

truncate clinic_hours cascade;
insert into clinic_hours (day,session,open_time,close_time,status) values ('Monday',1,'-','-','CLOSED');
insert into clinic_hours (day,session,open_time,close_time,status) values ('Tuesday',1,'9:00','12:00','OPEN');
insert into clinic_hours (day,session,open_time,close_time,status) values ('Tuesday',2,'16:00','19:00','OPEN');
insert into clinic_hours (day,session,open_time,close_time,status) values ('Wednesday',1,'9:00','12:00','OPEN');
insert into clinic_hours (day,session,open_time,close_time,status) values ('Wednesday',2,'16:00','19:00','OPEN');
insert into clinic_hours (day,session,open_time,close_time,status) values ('Thursday',1,'9:00','12:00','OPEN');
insert into clinic_hours (day,session,open_time,close_time,status) values ('Thursday',2,'16:00','19:00','OPEN');
insert into clinic_hours (day,session,open_time,close_time,status) values ('Friday',1,'9:00','12:00','OPEN');
insert into clinic_hours (day,session,open_time,close_time,status) values ('Friday',2,'16:00','19:00','OPEN');
insert into clinic_hours (day,session,open_time,close_time,status) values ('Saturday',1,'9:00','15:00','OPEN');
insert into clinic_hours (day,session,open_time,close_time,status) values ('Sunday',1,'9:00','12:00','OPEN');
truncate closures cascade;
insert into closures (start_date,end_date,reason,active,message,priority,closure_type,period_code) values ('2026-07-07','2026-07-13','ประชุมวิชาการ',true,'คลินิกปิดเนื่องจากประชุมวิชาการ',1,'CLOSE_ALL','ALL');
insert into closures (start_date,end_date,reason,active,message,priority,closure_type,period_code) values ('2026-10-25','2026-10-28','ประชุมวิชาการ',true,'คลินิกปิดเนื่องจากประชุมวิชาการ',1,'CLOSE_ALL','ALL');
insert into closures (start_date,end_date,reason,active,message,priority,closure_type,period_code) values ('2026-12-26','2027-01-04','หยุดปีใหม่',true,'คลินิกปิดช่วงเทศกาลปีใหม่',1,'CLOSE_ALL','ALL');
insert into closures (start_date,end_date,reason,active,message,priority,closure_type,period_code) values ('2026-08-16','2026-08-19','ประชุมวิชาการ',true,'คลินิกปิดเนื่องจากประชุมวิชาการ',1,'CLOSE_ALL','ALL');
insert into closures (start_date,end_date,reason,active,message,priority,closure_type,period_code) values ('2026-08-20','2026-08-20','ประชุมวิชาการ',true,'วันที่ 20 สิงหาคม คลินิกปิดช่วงเช้า และเปิดช่วงเย็นตามเวลาปกติ',1,'CLOSE_PERIOD','WD_AM');

truncate clinic_config cascade;
insert into clinic_config (key,value,category,source_sheet) values ('PHONE','085-065-9715','GENERAL','CLINIC_INFO') on conflict (key) do nothing;
insert into clinic_config (key,value,category,source_sheet) values ('TELEPHONE','0850659715','GENERAL','CLINIC_INFO') on conflict (key) do nothing;
insert into clinic_config (key,value,category,source_sheet) values ('LINE','@739fjvrr','GENERAL','CLINIC_INFO') on conflict (key) do nothing;
insert into clinic_config (key,value,category,source_sheet) values ('FACEBOOK','บ้านเด็ก','GENERAL','CLINIC_INFO') on conflict (key) do nothing;
insert into clinic_config (key,value,category,source_sheet) values ('PHONE_DISPLAY','085-065-9715','GENERAL','CLINIC_INFO') on conflict (key) do nothing;
insert into clinic_config (key,value,category,source_sheet) values ('PHONE_E164','+66850659715','GENERAL','CLINIC_INFO') on conflict (key) do nothing;
insert into clinic_config (key,value,category,source_sheet) values ('ADDRESS','41/59 ถนนกาญจนวิถี ต.บางกุ้ง อ.เมือง สุราษฏร์ธานี 84000','GENERAL','CLINIC_INFO') on conflict (key) do nothing;
insert into clinic_config (key,value,category,source_sheet) values ('LINE_OA_ID','@739fjvrr','GENERAL','CLINIC_INFO') on conflict (key) do nothing;
insert into clinic_config (key,value,category,source_sheet) values ('FACEBOOK_PAGE_NAME','บ้านเด็กคลินิก','GENERAL','CLINIC_INFO') on conflict (key) do nothing;
insert into clinic_config (key,value,category,source_sheet) values ('CLINIC_NAME','บ้านเด็กคลินิก','GENERAL','CLINIC_INFO') on conflict (key) do nothing;
insert into clinic_config (key,value,category,source_sheet) values ('LATITUDE','9.153356592','GENERAL','CLINIC_INFO') on conflict (key) do nothing;
insert into clinic_config (key,value,category,source_sheet) values ('LONGITUDE','99.35722506','GENERAL','CLINIC_INFO') on conflict (key) do nothing;
insert into clinic_config (key,value,category,source_sheet) values ('BOT_NAME','BAANDEK Vaccine Advisor','BOT','BOT_SETTING') on conflict (key) do nothing;
insert into clinic_config (key,value,category,source_sheet) values ('VERSION','Version 1.0','BOT','BOT_SETTING') on conflict (key) do nothing;
insert into clinic_config (key,value,category,source_sheet) values ('WEBSITE','https://bit.ly/baandek-vaccine','BOT','BOT_SETTING') on conflict (key) do nothing;
insert into clinic_config (key,value,category,source_sheet) values ('FOOTER','Powered by BAANDEK Vaccine Advisor','BOT','BOT_SETTING') on conflict (key) do nothing;
insert into clinic_config (key,value,category,source_sheet) values ('FALLBACK_MESSAGE','ขออภัยค่ะ น้องไดโนยังไม่เข้าใจคำถามที่พิมพ์มา 🦕น้องไดโนขอเวลาเรียนรู้เพิ่มเติม เพื่อให้สามารถตอบคำถามได้ตรงมากขึ้นในครั้งต่อไปค่ะระหว่างนี้ กรุณาลองเลือกเมนูด้านล่างตามเรื่องที่ต้องการทราบนะคะ','BOT','BOT_SETTING') on conflict (key) do nothing;
insert into clinic_config (key,value,category,source_sheet) values ('ASSISTANT_NAME','น้องไดโน','BOT','BOT_SETTING') on conflict (key) do nothing;
insert into clinic_config (key,value,category,source_sheet) values ('ASSISTANT_FULL_NAME','น้องไดโน — ผู้ช่วยบ้านเด็กคลินิก','BOT','BOT_SETTING') on conflict (key) do nothing;
insert into clinic_config (key,value,category,source_sheet) values ('PRODUCT_NAME','BAANDEK Vaccine Advisor','BOT','BOT_SETTING') on conflict (key) do nothing;
insert into clinic_config (key,value,category,source_sheet) values ('FACEBOOK_PAGE','BaanDekClinic','CONTACT','LINKS') on conflict (key) do nothing;
insert into clinic_config (key,value,category,source_sheet) values ('LINE_OA','@739fjvrr','CONTACT','LINKS') on conflict (key) do nothing;
insert into clinic_config (key,value,category,source_sheet) values ('GOOGLE_MAPS','https://bit.ly/baandek-map','CONTACT','LINKS') on conflict (key) do nothing;
insert into clinic_config (key,value,category,source_sheet) values ('VACCINE_ADVISOR','https://bit.ly/Baandek-VaccineApp','CONTENT','LINKS') on conflict (key) do nothing;

truncate faq cascade;
insert into faq (keyword,answer,category) values ('เวลาทำการ','กรุณาดูเวลาทำการล่าสุด','GENERAL');
insert into faq (keyword,answer,category) values ('ที่อยู่','https://maps.app.goo.gl/ZYxPBsuPB6tPJsQq9','GENERAL');
insert into faq (keyword,answer,category) values ('เบอร์โทร','085-065-9715','GENERAL');
insert into faq (keyword,answer,category) values ('RSV','RSV คือ...','VACCINE');
insert into faq (keyword,answer,category) values ('PCV20','วัคซีนป้องกันปอดอักเสบ...','VACCINE');

truncate packages cascade;
insert into packages (package_id,name,description,price,status) values ('BABY1','วัคซีนเด็กเล็ก','โปรแกรมวัคซีนปีแรก',35000,'INACTIVE');

truncate services cascade;
insert into services (title,description,icon,display_order,active) values ('ตรวจโรคทั่วไป','ดูแลอาการเจ็บป่วยของเด็ก ตั้งแต่แรกเกิดถึงวัยรุ่น','🩺',1,true);
insert into services (title,description,icon,display_order,active) values ('วัคซีนตามวัย','วางแผนวัคซีนหลักและวัคซีนทางเลือกให้เหมาะกับเด็กแต่ละคน','💉',2,true);
insert into services (title,description,icon,display_order,active) values ('เติบโตอย่างแข็งแรง','ติดตามการเจริญเติบโต พัฒนาการ โภชนาการ และทุกข้อกังวลของครอบครัว','🌱',3,true);

