#!/usr/bin/env python3
"""
BAANDEK ETL — Google Sheets HTML export  ->  clean Supabase seed.sql

Usage:
  python3 etl.py --db-dir ./vaccine_db --out ./db/seed.sql --report ./db/dq_report.txt

What it does
------------
1. Parses every <sheet>.html (Google "Publish to web / download as HTML" format).
2. Normalizes headers, drops blank rows / blank leading column.
3. Cleans + reshapes into the normalized schema (see db/schema.sql):
     - patients      : deduped from APPOINTMENTS by HN (last non-empty wins)
     - phone repair  : digits-only; restore leading 0 for 9-digit TH mobiles
     - appointments  : linked to patient by HN, purpose kept raw + best-effort vaccine_id
     - vaccine_aliases: AI_ALIAS comma-string exploded to one row per alias
     - clinic_config : BOT_SETTING + CLINIC_INFO + LINKS merged (category + source)
     - promotions    : PROMOS(kind=bot) + PROMOTIONS(kind=banner) merged
4. Emits idempotent-ish INSERTs (truncate + insert) to seed.sql.
5. Writes a data-quality report (dq_report.txt) with every fix + every flag.

No external services touched — pure transform. Review seed.sql before running it.
"""
import argparse, glob, os, re, sys
from bs4 import BeautifulSoup
from collections import defaultdict, Counter

# --------------------------------------------------------------------------- #
# Parsing helpers
# --------------------------------------------------------------------------- #
def load_grid(path):
    with open(path, encoding="utf-8") as fh:
        soup = BeautifulSoup(fh.read(), "lxml")
    t = soup.find("table")
    if not t:
        return []
    return [[td.get_text(strip=True) for td in tr.find_all(["td", "th"])]
            for tr in t.find_all("tr")]

def clean_sheet(db_dir, name):
    """Return (headers, list-of-dicts). Handles the leading col-letter column
    and an optional blank spacer row under the header."""
    path = os.path.join(db_dir, f"{name}.html")
    if not os.path.exists(path):
        return [], []
    grid = load_grid(path)
    if not grid:
        return [], []
    body = grid[1:]                      # drop the A,B,C column-letter row
    hdr_idx = next((i for i, r in enumerate(body) if any(c for c in r[1:])), None)
    if hdr_idx is None:
        return [], []
    headers = [c for c in body[hdr_idx][1:] if c != ""]
    rows = []
    for r in body[hdr_idx + 1:]:
        vals = r[1:1 + len(headers)]
        if any(v.strip() for v in vals):
            rows.append({h: (vals[i] if i < len(vals) else "") for i, h in enumerate(headers)})
    return headers, rows

# --------------------------------------------------------------------------- #
# Value cleaners
# --------------------------------------------------------------------------- #
def sql_str(v):
    if v is None or v == "":
        return "NULL"
    return "'" + str(v).replace("'", "''") + "'"

def sql_num(v):
    if v is None or str(v).strip() == "":
        return "NULL"
    s = re.sub(r"[^\d.\-]", "", str(v))
    return s if s not in ("", "-", ".") else "NULL"

def sql_bool(v):
    s = str(v).strip().upper()
    return "true" if s in ("TRUE", "YES", "1", "ACTIVE", "Y") else "false"

def sql_date(v):
    s = str(v).strip()
    m = re.match(r"(\d{4})-(\d{1,2})-(\d{1,2})", s)
    if m:
        y, mo, d = m.groups()
        return f"'{y}-{int(mo):02d}-{int(d):02d}'"
    return "NULL"

PHONE_FIX = {"fixed": 0, "already_ok": 0, "flagged": 0}
def repair_phone(raw):
    """Return (phone_or_None, is_valid). Restores leading 0 stripped by Sheets."""
    if not raw:
        return None, False
    d = re.sub(r"\D", "", str(raw))
    if len(d) == 10 and d.startswith("0"):
        PHONE_FIX["already_ok"] += 1
        return d, True
    if len(d) == 9:                       # leading zero eaten by Sheets numeric cast
        PHONE_FIX["fixed"] += 1
        return "0" + d, True
    PHONE_FIX["flagged"] += 1
    return (d or None), False

# --------------------------------------------------------------------------- #
# Main ETL
# --------------------------------------------------------------------------- #
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--db-dir", default="./vaccine_db")
    ap.add_argument("--out", default="./seed.sql")
    ap.add_argument("--report", default="./dq_report.txt")
    args = ap.parse_args()

    out, rep = [], []
    def emit(s=""): out.append(s)
    def log(s=""):  rep.append(s)

    emit("-- BAANDEK seed data — generated by etl.py. Review before running.")
    emit("-- Order respects FKs: vaccines -> patients -> appointments last.")
    emit("begin;")
    emit("set search_path = public;")
    emit()

    log("BAANDEK ETL — Data Quality Report")
    log("=" * 60)

    # ---- alias map (built first so appointments can resolve vaccine_id) -----
    _, dg_rows = clean_sheet(args.db_dir, "DISEASE_GROUP")
    alias_to_group = {}
    for r in dg_rows:
        grp = r.get("GROUP", "").strip()
        for a in (r.get("AI_ALIAS", "") or "").split(","):
            a = a.strip().lower()
            if a:
                alias_to_group.setdefault(a, grp)

    # =========================== VACCINES ===================================
    _, vac = clean_sheet(args.db_dir, "VACCINES")
    emit("truncate vaccines cascade;")
    for r in vac:
        emit(
            "insert into vaccines (vaccine_id,name,name_th,age_group,category,price,"
            "status,group_code,display_order,dose_name,description,catch_up,"
            "recommendation,warning,priority,product_code) values ("
            f"{sql_str(r.get('VaccineID'))},{sql_str(r.get('VaccineName'))},"
            f"{sql_str(r.get('VaccineNameT'))},{sql_str(r.get('AgeGroup'))},"
            f"{sql_str(r.get('Category'))},{sql_num(r.get('Price'))},"
            f"{sql_str((r.get('Status') or 'ACTIVE').upper())},{sql_str(r.get('GROUP'))},"
            f"{sql_num(r.get('DisplayOrder')) or 999},{sql_str(r.get('DoseName'))},"
            f"{sql_str(r.get('Description'))},{sql_str(r.get('CatchUp'))},"
            f"{sql_str(r.get('Recommendation'))},{sql_str(r.get('Warning'))},"
            f"{sql_str(r.get('Priority'))},{sql_str(r.get('ProductCode'))}) "
            "on conflict (vaccine_id) do nothing;")
    log(f"vaccines: {len(vac)} rows")
    # SAFETY: vaccine_id is PK, so multiple dose rows collapse to the first.
    # Warn if collapsed dose rows differ on fields we actually keep (price/desc/etc).
    from collections import defaultdict as _dd
    _by_vid = _dd(list)
    for r in vac:
        _by_vid[r.get("VaccineID")].append(r)
    _dose_warn = []
    for vid, rows in _by_vid.items():
        if len(rows) > 1:
            diffs = [f for f in ("Price", "Description", "CatchUp", "Recommendation", "Warning")
                     if len({(x.get(f) or "").strip() for x in rows}) > 1]
            if diffs:
                _dose_warn.append(f"{vid} ({len(rows)} doses): differing {', '.join(diffs)} — only dose 1 kept")
    if _dose_warn:
        log(f"  ⚠️ VACCINE DOSE COLLAPSE ({len(_dose_warn)}) — per-dose data lost by vaccine_id PK:")
        for w in _dose_warn:
            log(f"     - {w}")
    else:
        log("  ✓ dose collapse safe: no differing price/description across doses")
    # build name->id map for purpose resolution
    name_to_vid = {}
    for r in vac:
        for key in ("VaccineNameT", "VaccineName", "VaccineID", "ProductCode"):
            val = (r.get(key) or "").strip().lower()
            if val:
                name_to_vid.setdefault(val, r.get("VaccineID"))
    emit()

    # =========================== VACCINE_RULES ==============================
    _, rules = clean_sheet(args.db_dir, "VACCINE_RULES")
    emit("truncate vaccine_rules cascade;")
    for r in rules:
        emit(
            "insert into vaccine_rules (rule_id,vaccine_group,product_code,min_age_months,"
            "max_age_months,primary_doses,interval_days,booster_rule,eligibility,"
            "requires_history,doctor_review,display_message,status,sort_order,scenario_code) values ("
            f"{sql_str(r.get('RuleID'))},{sql_str(r.get('VaccineGroup'))},"
            f"{sql_str(r.get('ProductCode'))},{sql_num(r.get('MinAgeMonths'))},"
            f"{sql_num(r.get('MaxAgeMonths'))},{sql_num(r.get('PrimaryDoses'))},"
            f"{sql_num(r.get('IntervalDays'))},{sql_str(r.get('BoosterRule'))},"
            f"{sql_str(r.get('Eligibility'))},{sql_bool(r.get('RequiresHistory'))},"
            f"{sql_str(r.get('DoctorReview'))},{sql_str(r.get('DisplayMessage'))},"
            f"{sql_str((r.get('Status') or 'ACTIVE').upper())},"
            f"{sql_num(r.get('SortOrder')) or 999},{sql_str(r.get('ScenarioCode'))}) "
            "on conflict (rule_id) do nothing;")
    log(f"vaccine_rules: {len(rules)} rows")
    emit()

    # =========================== DISEASE_GROUP + ALIASES ====================
    emit("truncate disease_groups cascade;")
    emit("truncate vaccine_aliases cascade;")
    alias_count = 0
    for r in dg_rows:
        emit(
            "insert into disease_groups (vaccine,group_code,disease_group,status,display_order) values ("
            f"{sql_str(r.get('Vaccine'))},{sql_str(r.get('GROUP'))},"
            f"{sql_str(r.get('DISEASE_GROUP'))},"
            f"{sql_str((r.get('Status') or 'ACTIVE').upper())},"
            f"{sql_num(r.get('DisplayOrder')) or 999});")
    for alias, grp in alias_to_group.items():
        emit(
            "insert into vaccine_aliases (group_code,alias) values ("
            f"{sql_str(grp)},{sql_str(alias)}) on conflict do nothing;")
        alias_count += 1
    log(f"disease_groups: {len(dg_rows)} rows | vaccine_aliases exploded: {alias_count}")
    emit()

    # =========================== AGE_GUIDE ==================================
    _, ages = clean_sheet(args.db_dir, "AGE_GUIDE")
    emit("truncate age_guide cascade;")
    for r in ages:
        emit("insert into age_guide (age_code,display_name,sort_order) values ("
             f"{sql_str(r.get('AgeCode'))},{sql_str(r.get('DisplayName'))},"
             f"{sql_num(r.get('SortOrder')) or 999}) on conflict (age_code) do nothing;")
    log(f"age_guide: {len(ages)} rows")
    emit()

    # =========================== PATIENTS (dedupe from APPOINTMENTS) =========
    _, appts = clean_sheet(args.db_dir, "APPOINTMENTS")
    patients = {}                          # hn -> dict
    for r in appts:
        hn = (r.get("HN") or "").strip()
        if not hn:
            continue
        phone, valid = repair_phone(r.get("เบอร์ติดต่อ"))
        p = patients.setdefault(hn, {"hn": hn, "name": "", "nick": "", "phone": None,
                                     "valid": False, "addr": ""})
        # last non-empty wins
        if r.get("ชื่อสกุล"): p["name"] = r["ชื่อสกุล"]
        if r.get("ชื่อเล่น"): p["nick"] = r["ชื่อเล่น"]
        if r.get("ที่อยู่"):  p["addr"] = r["ที่อยู่"]
        if phone:            p["phone"], p["valid"] = phone, valid
    emit("truncate patients cascade;")
    for hn, p in patients.items():
        emit("insert into patients (hn,full_name,nickname,phone,phone_valid,address) values ("
             f"{sql_str(p['hn'])},{sql_str(p['name'] or '(unknown)')},{sql_str(p['nick'])},"
             f"{sql_str(p['phone'])},{str(p['valid']).lower()},{sql_str(p['addr'])}) "
             "on conflict (hn) do nothing;")
    log(f"patients: {len(patients)} unique HN (from {len(appts)} appointment rows -> "
        f"{len(appts)-len(patients)} duplicate person-rows collapsed)")
    log(f"phone repair: restored_leading_zero={PHONE_FIX['fixed']}, "
        f"already_ok={PHONE_FIX['already_ok']}, flagged_review={PHONE_FIX['flagged']}")
    emit()

    # =========================== APPOINTMENTS ===============================
    emit("truncate appointments cascade;")
    resolved, unresolved = 0, 0
    for r in appts:
        hn = (r.get("HN") or "").strip()
        purpose = (r.get("นัดเพื่อ") or "").strip()
        pl = purpose.lower()
        vid = None
        # best-effort purpose -> vaccine_id (exact name, then alias group's first vaccine)
        if pl in name_to_vid:
            vid = name_to_vid[pl]
        else:
            for nm, v in name_to_vid.items():
                if nm and nm in pl:
                    vid = v; break
        resolved += 1 if vid else 0
        unresolved += 0 if vid else 1
        patient_ref = (f"(select id from patients where hn={sql_str(hn)})" if hn else "NULL")
        emit(
            "insert into appointments (patient_id,hn,appt_date,time_slot,vaccine_id,"
            "purpose_raw,status,source) values ("
            f"{patient_ref},{sql_str(hn)},{sql_date(r.get('วันที่นัด'))},"
            f"{sql_str(r.get('เวลา'))},{sql_str(vid)},{sql_str(purpose)},"
            "'scheduled','sheet_import');")
    log(f"appointments: {len(appts)} rows | purpose->vaccine resolved={resolved}, "
        f"unresolved(kept raw)={unresolved}")
    emit()

    # =========================== CLINIC_HOURS / CLOSURES ====================
    _, hours = clean_sheet(args.db_dir, "CLINIC_HOURS")
    emit("truncate clinic_hours cascade;")
    for r in hours:
        emit("insert into clinic_hours (day,session,open_time,close_time,status) values ("
             f"{sql_str(r.get('Day'))},{sql_num(r.get('Session')) or 1},"
             f"{sql_str(r.get('Open'))},{sql_str(r.get('Close'))},{sql_str(r.get('Status'))});")
    log(f"clinic_hours: {len(hours)} rows")

    _, clos = clean_sheet(args.db_dir, "CLOSURES")
    emit("truncate closures cascade;")
    for r in clos:
        emit("insert into closures (start_date,end_date,reason,active,message,priority,"
             "closure_type,period_code) values ("
             f"{sql_date(r.get('Start'))},{sql_date(r.get('End'))},{sql_str(r.get('Reason'))},"
             f"{sql_bool(r.get('Active'))},{sql_str(r.get('Message'))},"
             f"{sql_num(r.get('Priority')) or 1},{sql_str(r.get('ClosureType'))},"
             f"{sql_str(r.get('PeriodCode'))});")
    log(f"closures: {len(clos)} rows")
    emit()

    # =========================== CLINIC_CONFIG (merge 3 sheets) =============
    # SAFETY: if the same key appears in >1 sheet with DIFFERENT values, we must
    # NOT silently drop one (old bug). We keep the first as the canonical key and
    # preserve any conflicting value under "{key}_{SHEET}", logging a warning.
    emit("truncate clinic_config cascade;")
    cfg_values = {}   # key -> (value, sheet)  canonical
    cfg_conflicts = []
    def emit_config(sheet, cat_default, key_col="Key", val_col="Value", cat_col=None):
        _, rows = clean_sheet(args.db_dir, sheet)
        n = 0
        for r in rows:
            k = (r.get(key_col) or "").strip()
            if not k:
                continue
            v = (r.get(val_col) or r.get("Url") or "").strip()
            cat = (r.get(cat_col) or cat_default) if cat_col else cat_default
            if k in cfg_values:
                prev_v, prev_sheet = cfg_values[k]
                if v and v != prev_v:                       # real conflict -> preserve both
                    alt_key = f"{k}_{sheet}"
                    cfg_conflicts.append(f"{k}: [{prev_sheet}]={prev_v[:40]!r} vs [{sheet}]={v[:40]!r} "
                                         f"-> kept canonical, added '{alt_key}'")
                    emit("insert into clinic_config (key,value,category,source_sheet) values ("
                         f"{sql_str(alt_key)},{sql_str(v)},{sql_str(cat)},{sql_str(sheet)}) "
                         "on conflict (key) do nothing;")
                    n += 1
                continue                                    # same value -> skip dup
            cfg_values[k] = (v, sheet)
            emit("insert into clinic_config (key,value,category,source_sheet) values ("
                 f"{sql_str(k)},{sql_str(v)},{sql_str(cat)},{sql_str(sheet)}) "
                 "on conflict (key) do nothing;")
            n += 1
        return n
    n1 = emit_config("CLINIC_INFO", "GENERAL")
    n2 = emit_config("BOT_SETTING", "BOT")
    n3 = emit_config("LINKS", "CONTACT", key_col="Key", val_col="Url", cat_col="Category")
    log(f"clinic_config: merged {n1}(CLINIC_INFO)+{n2}(BOT_SETTING)+{n3}(LINKS) "
        f"= {n1+n2+n3} keys")
    if cfg_conflicts:
        log(f"  ⚠️ CONFIG CONFLICTS PRESERVED ({len(cfg_conflicts)}) — differing values kept under *_SHEET keys:")
        for c in cfg_conflicts:
            log(f"     - {c}")
    emit()

    # =========================== PROMOTIONS (merge PROMOS + PROMOTIONS) =====
    emit("truncate promotions cascade;")
    _, promos = clean_sheet(args.db_dir, "PROMOS")
    for r in promos:
        emit("insert into promotions (kind,code,title,description,vaccine_group,discount,"
             "condition,active,start_date,end_date,display_period) values ('bot',"
             f"{sql_str(r.get('PromoID'))},{sql_str(r.get('PromoName'))},NULL,"
             f"{sql_str(r.get('VaccineGroup'))},{sql_str(r.get('Discount'))},"
             f"{sql_str(r.get('Condition'))},{sql_bool(r.get('Status'))},"
             f"{sql_date(r.get('StartDate'))},{sql_date(r.get('EndDate'))},"
             f"{sql_str(r.get('DisplayPeriod'))});")
    _, banners = clean_sheet(args.db_dir, "PROMOTIONS")
    for r in banners:
        emit("insert into promotions (kind,title,description,image_url,active,start_date,"
             "end_date) values ('banner',"
             f"{sql_str(r.get('Title'))},{sql_str(r.get('Description'))},"
             f"{sql_str(r.get('Image_URL'))},{sql_bool(r.get('Active'))},"
             f"{sql_date(r.get('Start_Date'))},{sql_date(r.get('End_Date'))});")
    log(f"promotions: {len(promos)}(bot) + {len(banners)}(banner) = {len(promos)+len(banners)}")
    emit()

    # =========================== simple content tables ======================
    def simple(sheet, table, colmap, transforms=None):
        _, rows = clean_sheet(args.db_dir, sheet)
        if not rows:
            log(f"{table}: 0 rows (sheet empty)"); return
        emit(f"truncate {table} cascade;")
        cols = list(colmap.values())
        for r in rows:
            vals = []
            for src, dst in colmap.items():
                v = r.get(src)
                fn = (transforms or {}).get(dst, sql_str)
                vals.append(fn(v))
            emit(f"insert into {table} ({','.join(cols)}) values ({','.join(vals)});")
        log(f"{table}: {len(rows)} rows")
        emit()

    simple("ARTICLES", "articles",
           {"Title": "title", "Category": "category", "Cover_Image_URL": "cover_image_url",
            "Content_Type": "content_type", "Panel_Images_Folder": "panel_images_folder",
            "Published": "published", "Body_Content": "body_content"},
           {"published": sql_bool})
    simple("FAQ", "faq", {"Keyword": "keyword", "Answer": "answer", "Category": "category"})
    simple("PACKAGES", "packages",
           {"PackageID": "package_id", "PackageName": "name", "Description": "description",
            "Price": "price", "Status": "status"},
           {"price": sql_num, "status": lambda v: sql_str((v or 'INACTIVE').upper())})
    simple("SERVICES", "services",
           {"Title": "title", "Description": "description", "Icon": "icon",
            "Order": "display_order", "Active": "active"},
           {"display_order": lambda v: sql_num(v) or 999, "active": sql_bool})
    simple("TEAM", "team",
           {"Name": "name", "Role": "role", "Photo_URL": "photo_url",
            "Credentials": "credentials", "Order": "display_order", "Active": "active"},
           {"display_order": lambda v: sql_num(v) or 999, "active": sql_bool})
    simple("REVIEWS", "reviews",
           {"Source": "source", "Reviewer_Name": "reviewer_name", "Text": "text",
            "Rating": "rating", "Screenshot_URL": "screenshot_url",
            "Permission_Confirmed": "permission_confirmed", "ReviewCount": "review_count"},
           {"rating": sql_num, "review_count": sql_num, "permission_confirmed": sql_bool})
    simple("VACCINE_NEWS", "vaccine_news",
           {"VaccineName": "vaccine_name", "StartDate": "start_date", "EndDate": "end_date",
            "Status": "status", "Description": "description"},
           {"status": sql_bool})

    emit("commit;")

    # ---- write files -------------------------------------------------------
    with open(args.out, "w", encoding="utf-8") as f:
        f.write("\n".join(out))
    with open(args.report, "w", encoding="utf-8") as f:
        f.write("\n".join(rep))
    print(f"✅ wrote {args.out} ({len(out)} lines)")
    print(f"✅ wrote {args.report}")
    print("\n".join(rep))

if __name__ == "__main__":
    main()
